---
title: "1.EDA: Caso 4"
author: "Sergio Cubero"

output: 
  html_document: 
    code_folding: hide
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, error = F, results = "asis")
options(scipen = 999)

library(summarytools)
library(tidyverse)

st_options(style='rmarkdown',
           plain.ascii = F,
           lang = "es"
           )
```



## Data

**Fuente:** BCCR

**Unidad de Análisis:** Curvas Semanales

**Variables:** Plazo en días (3600 variables) para cada curva semanal

```{r}
load("/cloud/project/CASO4/Data/DatosCurvaSoberana.RData")
```


## Analisis descriptivo 

```{r}
dfSummary(CurvSobWider)
```

```{r}
library(Hmisc)
describe(CurvSobWider)
```


## Curvas Soberanas

```{r}
ggplot(CurvSobLonger,aes(
    x = plazo_en_anos,
    y = tasa_percent,
    #fill = SemanaInicio,
    colour = SemanaInicio
  ) ) +
  geom_line() +
  scale_color_hue(direction = 1) +
  theme_minimal() +
  theme(legend.position = "none") +
  facet_wrap(as.factor(Anio)~.)
```

```{r}
ggplot(CurvSobLonger,aes(
    as.factor(plazo_en_dias),
    tasa_percent,
  ) ) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  theme_minimal() +
  theme(legend.position = "none") +
  facet_wrap(as.factor(Anio)~.,scales = 'free')
```





